<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</head> 
  
<body>
<div class="container-fluid bg-warning">
  <ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="#">Главная</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="showBooks.php">Список книг</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Добавить книгу</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Еще 1 пункт</a>
  </li>
</ul>

 <div>
    <p align="right"><img src="Books/image_560906170028049980771.jpg" width="72" height="77" style="vertical-align: middle;"/></p>
   <p align="right">Вы вошли как администратор</p>
</div>